name: Build (Windows) & optional Release (.exe)

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or tag to build'
        required: false
        default: 'main'
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Tauri CLI
        run: npm i -g @tauri-apps/cli

      - name: Install Dependencies
        run: npm ci

      - name: Build (Release)
        run: npm run build

      - name: Pack Windows Artifacts
        shell: bash
        run: |
          mkdir -p artifacts
          cp -R src-tauri/target/release/bundle/* artifacts/ || true
          cd artifacts
          7z a -tzip windows-bundle.zip *

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: artifacts

      - name: Create GitHub Release (only on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/windows-bundle.zip
            artifacts/**/*.msi
            artifacts/**/*.exe
            artifacts/**/*.zip
            artifacts/**/*.appx
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}